### PR TITLE
Resolves #79 fixes instructions text

### LINKED ISSUE #79: Instructions cut off
On the main game select screen, the instructions to press both black buttons to exit a game are cut off and not displayed fully.

### PR DESCRIPTION
**Pull request by charlottegeo**
Fixed issue with instructions text + descriptions text where text would cut off, also decreased y-spacing for text to 0.7f

### CODE REVIEW

File: onboard/frontend/ui/Menu.cs
Comment (MTFT-Games) [inline onboard/frontend/ui/Menu.cs:1]: I would like to see more appropriate defaults instead of 1f

File: onboard/frontend/ui/Menu.cs [hunk 1]
```diff
@@ -362,41 +371,23 @@ public class Menu : IMenu {
...
     }
 
 
     public void drawError(SpriteBatch _spriteBatch, SpriteFont font) {
         const string error = "Error: Could not get game list. Is API Down? Press both black buttons to reload.";
-        var instructions = wrapText(error, 25);
-        float instructSize = font.MeasureString(error).Y;
-        int lineNum = 0;
+        var instructions = wrapText(error, 35);
+        float instructSize = font.MeasureString(instructions[0]).Y;
```
Comment (MTFT-Games) [inline onboard/frontend/ui/Menu.cs]: It seems you have made the errors instead draw instructions

**Review by MTFT-Games — CHANGES_REQUESTED** [review]
Some things could be fixed before merge

**Review by MTFT-Games — APPROVED** [review]
Looks good! Sorry didnt re review last night. i needed sleep

**Review by MTFT-Games — CHANGES_REQUESTED** [review]
Actually, oops missed this, looks like you still have the issue of drawing instructions for errors

File: onboard/frontend/ui/Menu.cs (hunk 1 above)
Comment (MTFT-Games) [reply onboard/frontend/ui/Menu.cs]: I'm surprised this compiles actually, I don't think instructions[] exists here, isn't it locally scoped to drawInstructions and out of scope for drawError?

Comment (MTFT-Games) [reply onboard/frontend/ui/Menu.cs]: wait, no this was resolved, im just crazy and looking at the wrong commit

**Review by MTFT-Games — APPROVED** [review]
Looks good, im stupid and saw the issues still in a past commit
